title: Soulioli
description: Personal notes, projects, and reminders.
url: "https://soulioli.com"

# Makes URLs nice like /first-log-entry/ instead of /2026/02/24/...
permalink: /:title/

timezone: America/New_York

markdown: kramdown
kramdown:
  input: GFM

# Optional: auto-generate RSS feed (supported on GitHub Pages)
plugins:
  - jekyll-feed
